### ISSUE TITLE
Hibernate的Entity的Load Dirty的图片没有了

### ISSUE THREAD

**Issue by zxt47** [zhangzhenhuajack/spring-data-jpa-guide#11]
您好，这篇文章：
https://github.com/zhangzhenhuajack/spring-data-jpa-guide/wiki/SpringDataJpa%E4%B9%8BHibernate5.0%E7%9A%84Entity%E5%88%A4%E6%96%ADDirty%E7%9A%84%E8%BF%87%E7%A8%8B
的图片没有了。

**Comment by zhangzhenhuajack** [comment]
有反应图片没了，可以看: http://www.jackzhang.cn/spring-data-jpa-guide/SpringDataJpa%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95%E8%A1%A5%E5%85%85/SpringDataJpa%E4%B9%8BHibernate5.0%E7%9A%84Entity%E5%88%A4%E6%96%ADDirty%E7%9A%84%E8%BF%87%E7%A8%8B.html

**Comment by zxt47** [comment]
> 有反应图片没了，可以看: http://www.jackzhang.cn/spring-data-jpa-guide/SpringDataJpa%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95%E8%A1%A5%E5%85%85/SpringDataJpa%E4%B9%8BHibernate5.0%E7%9A%84Entity%E5%88%A4%E6%96%ADDirty%E7%9A%84%E8%BF%87%E7%A8%8B.html

好的，可以看到了，感谢您
