### ISSUE TITLE
我见过写的最烂的代码

### ISSUE THREAD

**Issue by pkzikao** [zhangzhenhuajack/spring-data-jpa-guide#13]
controller 没有返回值，没有日志，啥玩意，这水平还写书呢

**Comment by zhangzhenhuajack** [comment]
有些代码是伪代码

**Comment by pkzikao** [comment]
一共就没几行代码，还伪代码，真是担心作者的水平和诚意，文中自己的例子能不能跑得通都难说，这年代想出书赚钱都想疯了，一点下限也没有了
